import { EASINGS } from '../styles';
import type { SnippetOpts } from './snippet';

export type ExampleSpec = SnippetOpts & {
  id: string;
  label: string;
  bg: string;
};

export const EXAMPLES: readonly ExampleSpec[] = [
  {
    id: 'glitch',
    label: 'Glitch',
    bg: '#F9FAFB',
    text: '404',
    color: '#ffffff',
    appearColor: '#99A1AF',
    hoverColor: '#99A1AF',
    size: 3,
    speed: 40,
    fade: 80,
    easing: EASINGS[6],
    trail: 3,
    order: 'random',
    hoverStagger: 6,
    gap: 0,
  },
  {
    id: 'scanline',
    label: 'Scanline',
    bg: '#030806',
    text: 'SCAN',
    color: '#0B2A1C',
    appearColor: '#39FF14',
    hoverColor: '#F5FF7A',
    size: 3,
    speed: 28,
    fade: 260,
    easing: 'linear',
    trail: 8,
    order: 'ltr',
    hoverStagger: 3,
    gap: 1,
  },
  {
    id: 'beacon',
    label: 'Beacon',
    bg: '#111827',
    text: 'SOS',
    color: '#1F2937',
    appearColor: '#22C55E',
    hoverColor: '#86EFAC',
    size: 3,
    speed: 90,
    fade: 140,
    easing: 'linear',
    trail: 2,
    order: 'chars',
    hoverStagger: 8,
    gap: 0,
  },
  {
    id: 'neon',
    label: 'Neon',
    bg: '#0B1220',
    text: 'NEON',
    color: '#1E293B',
    appearColor: '#22D3EE',
    hoverColor: '#F472B6',
    size: 3,
    speed: 48,
    fade: 180,
    easing: EASINGS[5],
    trail: 4,
    order: 'random',
    hoverStagger: 10,
    gap: 1,
  },
  {
    id: 'ink',
    label: 'Ink',
    bg: '#FFF200',
    text: 'INK',
    color: '#1A0A00',
    appearColor: '#FF0055',
    hoverColor: '#7C3AED',
    size: 3,
    speed: 42,
    fade: 90,
    easing: EASINGS[6],
    trail: 6,
    order: 'chars',
    hoverStagger: 5,
    gap: 0,
  },
  {
    id: 'drift',
    label: 'Drift',
    bg: '#031018',
    text: 'WAVE',
    color: '#0E7490',
    appearColor: '#22F0FF',
    hoverColor: '#C084FC',
    size: 3,
    speed: 110,
    fade: 800,
    easing: EASINGS[5],
    trail: 7,
    order: 'ltr',
    hoverStagger: 24,
    gap: 0,
  },
  {
    id: 'spark',
    label: 'Spark',
    bg: '#1C1917',
    text: 'HOT',
    color: '#7C2D12',
    appearColor: '#F97316',
    hoverColor: '#FDE68A',
    size: 3,
    speed: 32,
    fade: 50,
    easing: 'linear',
    trail: 5,
    order: 'random',
    hoverStagger: 2,
    gap: 1,
  },
  {
    id: 'ghost',
    label: 'Ghost',
    bg: '#14001F',
    text: 'BOO',
    color: '#7C3AED',
    appearColor: '#FF4DF0',
    hoverColor: '#22F0FF',
    size: 3,
    speed: 64,
    fade: 520,
    easing: 'ease',
    trail: 2,
    order: 'random',
    hoverStagger: 28,
    gap: 0,
  },
];
